name: Create Archive
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '.git /node_modules/ .editorconfig'
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifact
          path: release.zip
      - name: Download Release Artifact
        uses: actions/download-artifact@v2
        with:
          name: Release Artifact
          path: .
      - uses: actions/checkout@v2
      - name: Build Release
        run: |
          # Commandes pour construire votre application et générer le fichier zip
      - name: Send Email
        uses: jakejarvis/send-email-action@v1.5.0
        with:
          from: votre-email@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: destinataire@gmail.com
          subject: "Nouvelle version de l'application disponible"
          body: "La nouvelle version de l'application est disponible en pièce jointe."
          attachments: release.zip
