on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '.git /node_modules/ .editorconfig'
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifact
          path: release.zip
      - name: Download Release Artifact
        uses: actions/download-artifact@v2
        with:
          name: Release Artifact
          path: .
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: lagoma.business@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Nouvelle version de l'application disponible"
          to: cjeanfabrice@gmail.com
          body: "La nouvelle version de l'application est disponible en pièce jointe."
          attachments: |
            release.zip
